# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: pgodschalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Biome CLI
        uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780 # v2.5.0

      - name: Run Biome
        run: biome ci

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@30a0e04f1870d58f8d717450cc6134995f993c63 # v21.0.0
        with:
          globs: "**/*.md"
